name: Build Repo UI

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Dependencies
        run: |
          npm install
          npm install -D lightningcss

      - name: Build Project
        env:
          NODE_OPTIONS: "--no-warnings" # ซ่อน DeprecationWarning (punycode) ไม่ให้ขึ้นกวนใจใน Log
        run: npm run build

      - name: Deploy Build to Branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: build-output
          force_orphan: true
