name: Build Repo UI

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # เปลี่ยนเป็น Node 22 แก้ปัญหา Deprecated

      - name: Install & Build
        run: |
          npm install    # ใช้ npm install เหมือนเดิม (ไม่ต้องใช้ package-lock.json)
          npm run build

      - name: Deploy Build to Branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: build-output
          force_orphan: true
